PR #43240: [XLA:CPU][oneDNN] Fix onednn_convolution_test build failure after move to restricted directory
Imported from GitHub PR https://github.com/openxla/xla/pull/43240

This PR fixes a build failure (error trace below) for `onednn_convolution_test` which started happening after https://github.com/openxla/xla/commit/e1b7988af67dd0c284a41c2ff42ce74021bdd1fb was merged.

```
xla/service/cpu/tests/restricted/onednn_convolution_test.cc:29:10: fatal error: 'xla/tsl/platform/cpu_info.h' file not found
   29 | #include "xla/tsl/platform/cpu_info.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Copybara import of the project:

--
80fc6d25a8e0fe27e6024988d0314c5df879a511 by Om Thakkar <om.thakkar@intel.com>:

fix onednn conv test build

Merging this change closes #43240

FUTURE_COPYBARA_INTEGRATE_REVIEW=https://github.com/openxla/xla/pull/43240 from Intel-tensorflow:othakkar/fix_onednn_conv_test_build 80fc6d25a8e0fe27e6024988d0314c5df879a511
PiperOrigin-RevId: 922078646